version: '3'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: employee_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: employee_db
      DB_PORT: 5432
      ALLOWED_ORIGINS: http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080

  frontend:
    build: ./frontend
    ports:
      - 3000:80
    depends_on:
      - backend
volumes:
  db-data:
